#!/usr/bin/env bash
# input
operation=${1};
PKG=("${@:2}");
# Configuration for Apt
APTCACHE=${APTCACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/apt};
APTSTATE=${APTSTATE:-${XDG_STATE_HOME:-$HOME/.local/state}/apt};
DPKGSTATE=${DPKGSTATE:-${XDG_STATE_HOME:-$HOME/.local/state}/dpkg};
APTCONFIG=${APTCONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/crackle};

# Configuration for Crackle
PKG_PATH=${PKG_PATH:-${XDG_DATA_HOME:-$HOME/.local/share}/crackle};
PKGS_DIR=${PKGS_DIR:-$PKG_PATH/$PKG};
CRACKLECMP=${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions;
CRACKDIR=${CRACKDIR:-$HOME/packages/$PKG};
CRACKLEBIN="https://gitlab.com/tuxecure/crackle-apt/cracklebin/-/archive/master/cracklebin-master.tar.gz"
PKG_PREFIX=${PKG_PREFIX:-$HOME/.local}
SCRP_DIR=$(dirname "${BASH_SOURCE[0]}")

# Set up aliases for apt commands
APTCONF="-o Dir::Etc=$APTCONFIG";
APT_GET="apt-get -o Dir::Cache=$APTCACHE -o Dir::State=$APTSTATE $APTCONF"
APT_CACHE="apt-cache -o Dir::Cache=$APTCACHE -o Dir::State=$APTSTATE -o Dir::Etc=$APTCONFIG"

# root check
if [[ "$EUID" -eq 0 ]]; then
    echo  "Crackle: please don't run me as root"
    exit 100
fi

# check if the files differ, if yes overwrite the old version
function upd() {
    lib=$(basename $1)
    if [[ ! -f "$2/$lib" && -d "$2" ]]; then
        if [[ $(basename $(dirname $1)) = "completions" ]] ; then
            say "Setting up bash_completions..." >&2
        else
            say "Installing $lib..." >&2
        fi
        cp $1 $2
    elif ! diff -q $1 $2; then
        if [[ $(basename $(dirname $1)) = "completions" ]] ; then
            say "Updating bash_completions..." >&2
        else
            say "Updating $lib..." >&2
        fi
        cp $1 $2
    fi
}

# load libraries
function load_library(){
    if [[ -f "$PKG_PREFIX/lib/$1" ]]; then
        [[ $(basename $SCRP_DIR) != "bin" ]] && upd $SCRP_DIR/lib/$1 $PKG_PREFIX/lib
        source "$PKG_PREFIX/lib/$1";
    else
        source "$SCRP_DIR/lib/$1";
    fi
}

function install_crackle() {
   mkdir -p $PKG_PREFIX/bin $PKG_PREFIX/lib/nix_config $CRACKLECMP
   if [[ ! $SCRP_DIR = $PKG_PREFIX/bin ]]; then
       # install the bins
       upd $SCRP_DIR/arch_triplet $PKG_PREFIX/bin;
       upd $SCRP_DIR/crackle $PKG_PREFIX/bin
       upd $SCRP_DIR/desktop_trunc $PKG_PREFIX/bin
       upd $SCRP_DIR/_crackleopts $PKG_PREFIX/bin;
       upd $SCRP_DIR/remount $PKG_PREFIX/bin;
       upd $SCRP_DIR/rorw $PKG_PREFIX/bin;
       upd $SCRP_DIR/nix-manager $PKG_PREFIX/bin;
       # install the libs
       upd $SCRP_DIR/lib/basefunc $PKG_PREFIX/lib;
       upd $SCRP_DIR/lib/nix_config/__init__.py $PKG_PREFIX/lib/nix_config;
       upd $SCRP_DIR/lib/nix_config/config.py $PKG_PREFIX/lib/nix_config;
       upd $SCRP_DIR/lib/nix_config/nix_config.py $PKG_PREFIX/lib/nix_config;
       upd $SCRP_DIR/lib/nix_config/nix_interact.py $PKG_PREFIX/lib/nix_config;
       upd $SCRP_DIR/lib/nix_config/openprocess.py $PKG_PREFIX/lib/nix_config;
       upd $SCRP_DIR/lib/clickfunc $PKG_PREFIX/lib;
       upd $SCRP_DIR/lib/setupfunc $PKG_PREFIX/lib;
       upd $SCRP_DIR/lib/sudofunc $PKG_PREFIX/lib;
       # setup bash completion
       upd $SCRP_DIR/share/bash-completion/completions/crackle $CRACKLECMP;
   fi
}

load_library basefunc;

# reclaim storage space
function clean() {
    nix-collect-garbage;
    load_library setupfunc;
    pkgunset;
}

# update packages
function update() {
    nix-channel --update;
    home-manager switch;
}

# list installed packages
function list() {
    nix-manager list
}

# View information about Crackle, don't do anything
function debug(){
    echo "CRACKLE CONFIG"
	echo "PKG_PATH: '$PKG_PATH'"
	echo "PKG_PREFIX: '$PKG_PREFIX'"
	echo "PKGS_DIR: '$PKGS_DIR'"
	echo "CRACKLECMP: '$CRACKLECMP'"
	echo "CRACKDIR: '$CRACKDIR'"
	echo "APT CONFIG"
	echo "APTCONFIG: '$APTCONFIG'"
	echo "APTCACHE: '$APTCONFIG'"
	echo "APTSTATE: '$APTSTATE'"
	echo "APT_GET: '$APT_GET'"
	echo "APT_CACHE: '$APT_CACHE'"
	echo "DPKGSTATE: '$DPKGSTATE'"
}

function crack() {
    load_library setupfunc;
    pkgsetup;
    load_library clickfunc;
    setup_curlxz;
    $APT_GET clean;
    setup_repos;
    $APT_GET update;
    $APT_GET install --download-only ${PKG[@]};
    extract_deb_to ${CRACKDIR};
    pkgunset;
}

# Help
function show_help(){
	echo 'available commands:
	- crackle sudo $BIN
	- crackle sudok $BIN
	- crackle setup
	- crackle clean
	- crackle update
	- crackle debug
	- crackle list
	- crackle crack
	- crackle click $PKG
	- crackle help'
	exit 0
}

case $operation in
	"sudo")[ -z "$PKG" ] && err "missing argument";load_library sudofunc;[ $PKG = "debug" ] && debug;enable_sudo;;
	"sudok")[ -z "$PKG" ] && err "missing argument";load_library sudofunc;[ $PKG = "debug" ] && debug;disable_sudo;;
    "setup") install_crackle;load_library setupfunc;setup;;
    "clean") clean;;
    "update") update;;
    "debug") debug;;
    "list") list;;
    "crack") crack;;
	"click")[ -z "$PKG" ] && err "missing argument";load_library clickfunc;[ $PKG = "debug" ] && debug;build_click;;
	"help")show_help;;
	*) show_help;;
esac
