#!/bin/bash
_crackle()
{
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case $COMP_CWORD in
	    1) COMPREPLY=( $(compgen -W "$(crackle |awk '/setup/,/nuke/{print $3}')" -- ${cur}) );;
	    *);;
    esac
    case $prev in
	    install|download|crack|show) COMPREPLY=( $( apt-cache --no-generate pkgnames "$cur" 2> /dev/null ) );;
    esac

    return 0
}
complete -F _crackle crackle

readarray -t completions < <(ls "$PKG_PATH"/etc/bash_completion.d/* "$PKG_PATH"/usr/share/bash-completion/completions/*);
for completion in ${completions[@]}
do
. $completion
done;
