#!/bin/bash
operation=$1;
PKG=$2
PKG_PATH=${PKG_PATH:-${XDG_DATA_HOME:-$HOME/.local/share}/crackle};
PKG_PREFIX=${PKG_PREFIX:-$HOME/.local}
SCRP_DIR=$(dirname "${BASH_SOURCE[0]}")
if [[ -f "$PKG_PREFIX/lib/triplet" ]]; then
    source "$PKG_PREFIX/lib/triplet";
else
    source "$SCRP_DIR/lib/triplet";
fi

# Help
if [ -z "$operation" -o "$operation" = "help" ]; then
	echo 'available commands:
	- crackle setup
	- crackle debug
	- crackle install $PKG
	- crackle download $PKG
	- crackle crack $PKG
	- crackle remove $PKG
	- crackle clean
	- crackle search $PKG
	- crackle show $PKG
	- crackle update
	- crackle nuke'
	exit 0
fi

case $operation in
	"install"|"reinstall"|"download"|"crack"|"remove"|"search"|"show")[ -z "$PKG" ] && err "missing argument";;
	"setup"|"debug"|"clean"|"update"|"nuke");;
	*) err 'available operations (setup|debug|install $PKG|download $PKG|crack $PKG|remove $PKG|clean|search $PKG|show $PKG|update)';;
esac

# Configuration for Apt
PKGS_DIR=${PKGS_DIR:-$PKG_PATH/var/log};

APTCACHE=${APTCACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/crackle};
APTSTATE=${APTSTATE:-${XDG_STATE_HOME:-$HOME/.local/state}/crackle};
APTCONFIG=${APTCONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/crackle};

# Configuration for Crackle
CRACKLERC=$APTCONFIG/cracklerc;
CRACKLEENV=$APTCONFIG/environment;
CRACKLECMP=${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions;
CRACKDIR=${CRACKDIR:-$HOME/packages/$PKG};

# Aliases for commands
APT_GET="apt-get -o Dir::Cache=$APTCACHE -o Dir::State=$APTSTATE -o Dir::Etc=$APTCONFIG"
APT_CACHE="apt-cache -o Dir::Cache=$APTCACHE -o Dir::State=$APTSTATE -o Dir::Etc=$APTCONFIG"

# Root check
[ "$EUID" = "0" ] && {
    echo "Don't run me as root, please"
    exit 32;
}

# View information about Crackle, don't do anything
[ "$operation" = "debug" ] && {
	echo "PKG_PATH: '$PKG_PATH'"
	echo "PKG_PREFIX: '$PKG_PREFIX'"
	echo "PKGS_DIR: '$PKGS_DIR'"
	echo "APT_CACHE: '$APT_CACHE'"
	echo "APTCONFIG: '$APTCONFIG'"
	echo "APTCACHE: '$APTCONFIG'"
	echo "APTSTATE: '$APTSTATE'"
	echo "CRACKLERC: '$CRACKLERC'"
	echo "CRACKLEENV: '$CRACKLEENV'"
	echo "CRACKLECMP: '$CRACKLECMP'"
	echo "CRACKDIR: '$CRACKDIR'"
	echo "APT_GET: '$APT_GET'"
	echo "APT_CACHE: '$APT_CACHE'"
	exit 0;
}

# Cleans up a package's luggage
[ "$operation" = "clean" ] && {
    $APT_GET "$operation";
    find "$PKG_PATH" -xtype l -exec rm {} +;
    exit 0;
}

# Reads configuration for Crackle
[ "$operation" = "setup" ] && {
    bashrc=$(grep crackle "$HOME"/.bashrc);
    profile=$(grep crackle "$HOME"/.profile);

    [[ -d "$PKG_PATH" ]] || mkdir -p "$PKG_PATH";
    [[ -d "$PKGS_DIR" ]] || mkdir -p "$PKGS_DIR";
    # install crackle in ~/.local
    mkdir -p "$PKG_PREFIX/bin" "$PKG_PREFIX/lib";
    #TRANSISTION to the new structure
    [[ ! -e "$PKG_PREFIX/bin/crackle" ]] && rm "$PKG_PREFIX/bin/crackle" ;
    cp $SCRP_DIR/crackle $PKG_PREFIX/bin;
    #TRANSISTION to the new structure
    [[ -e "$PKG_PATH/bin/crackle" ]] && rm "$PKG_PATH/bin/crackle";
    cp $SCRP_DIR/lib/* $PKG_PREFIX/lib;
    #TRANSISTION to the new structure
    [ -d $PKG_PATH/lib ] && rm -r $PKG_PATH/lib;

    diff -q $PKG_PREFIX/lib/triplet $SCRP_DIR/lib/triplet || {
        source $SCRP_DIR/lib/triplet
        upd $SCRP_DIR/lib/triplet $PKG_PREFIX/lib
    }

    [[ -d "$APTCACHE" ]] || mkdir -p "$APTCACHE";
    [[ -d "$APTSTATE" ]] || mkdir -p "$APTSTATE";
    #TRANSISTION to the new structure
    [[ -d "$APTCACHE/lists" ]] && rm -r "$APTCACHE/lists";
    [[ -d "$APTCONFIG" ]] || {
        mkdir -p $APTCONFIG/sources.list.d $APTCONFIG/preferences.d;
        ln -s /etc/apt/sources.list $APTCONFIG;
    }
    [[ -f "$CRACKLERC" ]] || {
        echo "CRACKLEENV=$CRACKLEENV" > "$CRACKLERC";
	[ -d $CRACKLEENV ] || mkdir $CRACKLEENV;
        cat "$SCRP_DIR"/cracklerc >> "$CRACKLERC";
    }
    [[ -z "$bashrc" ]] && {
        echo Amending ~/.bashrc...;
        $SCRP_DIR/awkfig -v start="#cracklerc" "$SCRP_DIR"/crackle.conf >> "$HOME"/.bashrc;
    }
    [[ -z "$profile" ]] && {
        echo Amending ~/.profile...;
        $SCRP_DIR/awkfig -v start="#cracklerc" "$SCRP_DIR"/crackle.conf >> "$HOME"/.profile;
    }
    diff -q $PKG_PREFIX/bin/crackle $SCRP_DIR/crackle || upd $SCRP_DIR/crackle $PKG_PREFIX/bin
    diff -q $PKG_PREFIX/lib/loginfo $SCRP_DIR/lib/loginfo || upd $SCRP_DIR/lib/loginfo $PKG_PREFIX/lib
    #TRANSISTION to the new structure
    [[ -d "$PKG_PATH/bin/scripts" ]] && rm -r "$PKG_PATH/bin/scripts";
    [[ -d "$PKG_PREFIX/bin/scripts" ]] || mkdir -p "$PKG_PREFIX/bin/scripts";
    #TRANSISTION to the new structure
    [[ -f "$APTCONFIG/crackle_completion" ]] && rm "$APTCONFIG/crackle_completion";
    [[ -d "$CRACKLECMP" ]] || {
        echo Setting up bash_completions...;
	mkdir -p $CRACKLECMP;
        cp "$SCRP_DIR/crackle_complete" $CRACKLECMP/crackle;
    }
    [[ ! "$(grep completions "$HOME"/.bash_completion)" ]] && {
        echo setting up bash completion.
        $SCRP_DIR/awkfig -v start="#cracklecmp" "$SCRP_DIR"/crackle.conf >> $HOME/.bash_completion; 
    }
    [ -d "$APTSTATE/lists" ] || {
        echo Fetching package lists...;
        "$SCRP_DIR"/crackle update || exit 100;
    }
    cp -r "$SCRP_DIR"/bin/* "$PKG_PREFIX/bin/scripts"
    if ! check_cmd patchelf; then "$SCRP_DIR"/crackle install patchelf; fi
    echo "Setup complete!";
    exit 0;
}

# Updates the apt repositories
[ "$operation" = "update" ] && {
        wget -q --spider https://ubports.com || err "no internet connection, please run crackle update later to fetch the latest package lists";
        $APT_GET "$operation"|| err "crackle works best with a readonly rootfs please remount your rootfs";
        exit 0;
}

# Downloads a package for installation
[ "$operation" = "download" ] && {
        $APT_GET "$operation" "$PKG";
        exit 0;
}

# View information about a package
[[ "$operation" = "search" || "$operation" = "show" ]] && {
        $APT_CACHE "$operation" "$PKG";
        exit 0;
}

# Install a package for the user
[[ "$operation" = "install" || "$operation" = "crack" ]] && {
    if [[ "$operation" = "crack" ]]; then
        dir="$CRACKDIR";
    else
        dir="$PKG_PATH";
    fi
    [[ "$operation" = "crack" && ! -d "$dir" ]] && mkdir "$dir";
    [ "$operation" = "install" ] && {
            [ -d "$PKG_PATH" ] || err "$PKG_PATH does not exist, please run crackle setup first";
    }
    [[ -d "$PKGS_DIR/$PKG" && "$operation" = "install" ]] && {
        echo "Fetching installed version...";
        installed=$(cat $PKGS_DIR/$PKG/pkgs.version);
        echo "Fetching candidate version...";
        candidate=$($APT_CACHE policy $PKG|awk '/Candidate/{print $2}');
        echo "Comparing...";
        [[ "$installed" = "$candidate" ]] && { echo "$PKG" is already the newest version \($installed\); exit 0; }
    }
    $APT_GET install --download-only "$PKG" || {
            [ $? = 1 ] && exit 1;
	    err "if the above error is complaining about permission denied, do not run with sudo crackle doesn't require root! please remount your rootfs as readonly instead";
    };
    readarray -t packages < <(ls "$APTCACHE"/archives/*.deb);
    TRIPLET=$(get_architecture);
    . "$PKG_PREFIX/lib/loginfo";
    for package in "${packages[@]}"
    do
        get_pkg_info $package;
        [[ "$operation" = "install" ]] && log_pkg_info "$package";
	echo Unpacking $pkgname "("$pkgversion")"
        dpkg-deb -x "$package" "$dir";
	[[ -f "$PKG_PREFIX/bin/scripts/$pkgname" ]] && { echo Setting up $pkgname; PKG_PATH=$PKG_PATH PKG_PREFIX=$PKG_PREFIX TRIPLET=$TRIPLET CRACKLEENV=$CRACKLEENV/$pkgname "$PKG_PREFIX/bin/scripts/$pkgname"; };
    done;
    link_bin;
    link_bash-completion;
    echo Cleaning packages...
    $APT_GET clean;
    echo Done!
    exit 0;
}

# reinstall a package
[[ "$operation" = "reinstall" ]] && {
    rm -r $PKGS_DIR/$PKG;
    crackle install $PKG;
}

# remove crackle from the system
[[ "$operation" = "nuke" ]] && {
    [ -d $PKG_PATH ] && rm -r $PKG_PATH;
    [[ -d "$APTCACHE" ]] && rm -r "$APTCACHE";
    [[ -d "$APTSTATE" ]] && rm -r "$APTSTATE";
    [[ -d "$PKG_PATH" ]] && rm -r "$PKG_PATH";
    [[ -d "$APTCONFIG" ]] && rm -r "$APTCONFIG";
    [[ -f "$PKG_PREFIX/bin/crackle" ]] && rm $PKG_PREFIX/bin/crackle;
    [[ -f "$CRACKLECMP/crackle" ]] && rm $CRACKLECMP/crackle;
    find "$PKG_PREFIX/bin" -xtype l -exec rm {} +;
    find "$CRACKLECMP" -xtype l -exec rm {} +;
    echo please check ~/.profile ~/.bashrc and ~/.bash_completion for leftover references to crackle
    exit 0;
}

# Delete a package from the user path
[[ "$operation" = "remove" ]] && {
    [ -d "$PKGS_DIR/$PKG" ] || err "$PKG is not installed";
    . "$PKG_PREFIX/lib/loginfo";
    echo Building dependency tree...;
    readarray -t dependencies < <($APT_CACHE depends "$PKG"| awk '/Depends/{print $2}'|uniq);
    for dependency in "${dependencies[@]}"
    do
	[ -d "$PKGS_DIR/$dependency" ] || dependencies=(${dependencies[@]/$dependency});
	[ -d "$PKGS_DIR/$dependency" ] && {
		fetch_rdependencies
	}
    done
    echo the following packages would be removed: ${packages[@]};
    exit 0;
    [ -f "$CRACKLEENV/$PKG" ] && rm $CRACKLEENV/$PKG;
    for dependency in "${dependencies[@]}"
    do
            rmpkgtree $dependency;
    done;
    exit 0;
}
