#!/usr/bin/python3
import sys, os
home = os.getenv('HOME')
sys.path.append(home + '/.local/lib')
import nix_config.nix_config as config
import nix_config.nix_interact
from nix_config.openprocess import openprocess
from nix_config.openprocess import Spinner
from sys import argv

package = config.read_packages()

if len(argv) > 1 and argv[1] == 'list':
    operation = argv[1]
elif len(argv) > 1 and argv[1] == 'clean':
    operation = argv[1]
elif len(argv) > 1 and argv[1] == 'update':
    operation = argv[1]
elif len(argv) > 2:
    operation = argv[1]
    pkg = argv[2:]
else:
    print('argument missing')
    exit(1)

if operation == 'list':
    for pkg in package:
        pkg=pkg.split('.')
        pkg='.'.join(pkg[1:])
        print(pkg)
elif operation == 'install':
    packages = [f'pkgs.{package}' for package in pkg]
    with Spinner(f"Installing {', '.join(pkg)}", "done!\n"):
        added, [stdout, simple_errors, full_errors] = config.add_packages( packages )
    if simple_errors:
        print()
        for err in full_errors:
            print(err)
    else:
        with Spinner(f"Activating", "done!\n"):
            openprocess('home-manager switch')

elif operation == 'remove':
    packages = [f'pkgs.{package}' for package in pkg]
    with Spinner(f"Removing {', '.join(pkg)}", 'done!\n'):
        removed, [stdout, simple_errors, full_errors] = config.delete_packages( packages )
    if simple_errors:
        print()
        for err in full_errors:
            print(err)
    else:
        with Spinner('Deactivating', 'done!\n'):
            openprocess('home-manager switch')
        with Spinner('Cleaning up', 'done!\n'):
            output , full_error = openprocess('nix-collect-garbage -d')
            for stdout in output:
                print(f'\r{stdout}', end='')
            print()
elif operation == 'clean':
    with Spinner('Cleaning up', 'done!\n'):
        output , full_error = openprocess('nix-collect-garbage -d')
        for stdout in output:
            print(f'\r{stdout}', end='')
        print()
        openprocess('nix-store --optimise')
elif operation == 'update':
    with Spinner('Updating', 'done!\n'):
        openprocess('nix-channel --update')
    with Spinner('Activating', 'done!\n'):
        openprocess('home-manager switch')
