#!/usr/bin/python3
import sys, os
home = os.getenv('HOME')
sys.path.append(home + '/.local/lib')
import nix_config.nix_config as config
import nix_config.nix_interact
from nix_config.openprocess import openprocess
from sys import argv

package = config.read_packages()

if len(argv) > 1 and argv[1] == 'list':
    operation = argv[1]
elif len(argv) > 2:
    operation = argv[1]
    pkg = argv[2]
else:
    print('argument missing')
    exit(1)

if operation == 'list':
    for pkg in package:
        pkg=pkg.split('.')
        pkg='.'.join(pkg[1:])
        print(pkg)
elif operation == 'install':
    print('Installing '+ pkg + '...')
    added, [stdout, simple_errors, full_errors] = config.add_packages( ['pkgs.' + pkg] )
    if simple_errors:
        for err in full_errors:
            print(err)
    else:
        print('...')
        openprocess('home-manager switch')
        print('Done!')

elif operation == 'remove':
    print('Removing '+ pkg + '...')
    removed, [stdout, simple_errors, full_errors] = config.delete_packages( ['pkgs.' + pkg] )
    if simple_errors:
        for err in full_errors:
            print(err)
    else:
        print('...')
        openprocess('home-manager switch')
        print('Done!')
