#!/usr/bin/awk -f
BEGIN {
	FS = "[ ,]"
	ARGC=2;
	ARGV[1]="/proc/mounts";
	system("sudo -K");
}
{
	if ( $2 == "/" && $3 != "rootfs" ) {
		rootfs = $4;
		if ( rootfs == "ro" ) {
			print "remounting rootfs as readwrite";
			system("set -x; sudo mount -t tmpfs tmpfs /var/lib/apt");
			system("set -x; sudo mount -t tmpfs tmpfs /var/cache/apt");
			system("set -x; sudo mount -o remount,rw /");
		}
		if ( rootfs == "rw" ) {
			print "remounting rootfs as readonly";
			system("set -x; sudo mount -o remount,ro /");
		}
	}
	if ( /apt/  && rootfs == "rw" ) {
			system("set -x; sudo umount "$2);
	}
}
END {
	system("sudo -K");
}
