#!/usr/bin/env bash

function pkg_arch() {
	for pkg in "${PKG[@]}"
	do
		if [[ "${pkg}" == *":all" ]]; then
			dpkgs+="${pkg} "
		else
			dpkgs+="${pkg}":"${ARCH} "
		fi
	done
	echo ${dpkgs};
}

# extract deb file to a directory
function extract_deb() {
    while read package
    do
        say "extracting $package";
        dpkg-deb -x "${package}" "${BUILD_DIR}";
    done < <(ls "$APTCACHE"/archives/*.deb);
}

function prepare_apt() {
    pkgsetup;
    [ -d "${APTSTATE}/lists" ] || {
        say "Fetching package lists...";
        mkdir -p ${APTSTATE}/lists/partial ${APTCACHE}/archives/partial;
        $APT_GET update;
    }
    $APT_GET install --download-only $(pkg_arch);
}

function build_click () {
    if ! check_cmd click; then err "missing click"; fi
    cd ${ROOT};
    [[ ! -f "manifest.json" && ! -f "manifest.json.in" ]] && err "missing manifest.json";
    [ -d "${BUILD_DIR}" ] && rm -r ${BUILD_DIR}
    ensure prepare_apt;
    extract_deb;
    if [ ! -f "manifest.json.in" ]; then
        say "Preparing build environment..."
        prep_build;
    fi
    say "Building package tree..."
    [ -d ${CLICK_LD_LIBRARY_PATH} ] || mkdir -p ${CLICK_LD_LIBRARY_PATH} ${CLICK_PATH}
    [ -d ${BUILD_DIR}/lib ] && cp -r ${BUILD_DIR}/lib/* ${CLICK_LD_LIBRARY_PATH}
    [ -d ${BUILD_DIR}/usr/lib ] && cp -r ${BUILD_DIR}/usr/lib/* ${CLICK_LD_LIBRARY_PATH}
    [ -d ${CLICK_LD_LIBRARY_PATH}/${ARCH_TRIPLET} ] && { cp -r ${CLICK_LD_LIBRARY_PATH}/${ARCH_TRIPLET}/* ${CLICK_LD_LIBRARY_PATH};rm -rf ${CLICK_LD_LIBRARY_PATH}/${ARCH_TRIPLET}; }
    [ -d ${BUILD_DIR}/usr/bin ] && cp -r ${BUILD_DIR}/usr/bin/* ${CLICK_PATH}
    [ -d ${BUILD_DIR}/usr/sbin ] && cp -r ${BUILD_DIR}/usr/sbin/* ${CLICK_PATH}
    [ -d ${BUILD_DIR}/usr/share ] && cp -r ${BUILD_DIR}/usr/share ${INSTALL_DIR}
[ -d ${BUILD_DIR}/usr/games ] && cp -r ${BUILD_DIR}/usr/games/* ${CLICK_PATH}
    if [ -f "manifest.json" ]; then
        ROOT=$ROOT ARCH=$ARCH ARCH_TRIPLET=$ARCH_TRIPLET BUILD_DIR=$BUILD_DIR INSTALL_DIR=$INSTALL_DIR CLICK_LD_LIBRARY_PATH=$CLICK_LD_LIBRARY_PATH CLICK_PATH=$CLICK_PATH bash ${BUILD_DIR}/adapt.sh
	sed -i "s/@CLICK_ARCH@/${ARCH}/" ${INSTALL_DIR}/manifest.json
    fi
    if [[ -z $CI ]]; then
        say "Building click...";
        click build ${INSTALL_DIR}
    fi
    pkgunset;
    exit 0;
}

function prep_build () {
	[ -d "${INSTALL_DIR}" ] && rm -r ${INSTALL_DIR}
	mkdir -p ${CLICK_LD_LIBRARY_PATH} ${CLICK_PATH} ${INSTALL_DIR}
	fetch_desktop ${BUILD_DIR} ${INSTALL_DIR};
	mod_desktop
	cp ${ROOT}/pkg.d/* ${ROOT}/apparmor.json ${ROOT}/manifest.json ${BUILD_DIR}/ || exit 1
	sed -i "s/@pkg@/${PKG}/" ${BUILD_DIR}/manifest.json
	cp ${BUILD_DIR}/*.json ${INSTALL_DIR}
	cp ${BUILD_DIR}/pkg.sh ${CLICK_PATH}/${PKG}.sh
}

mod_desktop(){
	desktopfile=$(find ${INSTALL_DIR} -maxdepth 1 -name *${PKG}*.desktop)
	sed -i "/Icon=/d" $desktopfile
	sed -i "/Exec=/d" $desktopfile
	sed -i "/^Categories=/i Exec=${PKG}.sh" $desktopfile;
	mv $desktopfile ${INSTALL_DIR}/${PKG}.desktop
}

function fetch_desktop() {
	PKG_DIR=$1
	PKG_DESKTOP=$2
	while read desktop
	do
		desktopname=$(basename $desktop)
		${SCRP_DIR}/desktop_trunc $desktop > ${PKG_DESKTOP}/crackle.${desktopname}
		echo "X-Ubuntu-Touch=true" >>  ${PKG_DESKTOP}/crackle.${desktopname}
        done < <(find $PKG_DIR -name *.desktop)
}

