#!/usr/bin/env bash

# set up files and directories for the functioning of apt on a ro rootfs
function pkgsetup(){
    [[ -d "$DPKGSTATE" ]] || {
        mkdir -p "$DPKGSTATE";
        cp /var/lib/dpkg/status $DPKGSTATE/status;
    }

    [[ -d "$APTCACHE" ]] || mkdir -p "$APTCACHE";
    [[ -d "$APTSTATE" ]] || mkdir -p "$APTSTATE";

    [[ -d "$APTCONFIG" ]] || {
        mkdir -p $APTCONFIG/sources.list.d $APTCONFIG/preferences.d $APTCONFIG/trusted.gpg.d;
        if [[ $(lsb_release -cs) = "focal" ]]; then
            ln -s /etc/apt/sources.list $APTCONFIG;
        elif [[ $(lsb_release -cs) = "noble" ]];then
            ln -s /etc/apt/sources.list.d/* $APTCONFIG/sources.list.d;
        fi
        [[ -n "$(ls /etc/apt/trusted.gpg.d)" ]] && ln -s /etc/apt/trusted.gpg.d/* $APTCONFIG/trusted.gpg.d/;
    }
}

# now that we've used curl and xz there is no need to keep them around, nuke them
function pkgunset(){
    if [ -d $PKG_PATH ]; then rm -r $PKG_PATH; fi
    if [ -d $APTCACHE ]; then rm -r $APTCACHE; fi
    if [ -d $APTCONFIG ]; then rm -r $APTCONFIG; fi
    if [ -d $APTSTATE ]; then rm -r $APTSTATE; fi
    if [ -d $DPKGSTATE ]; then rm -r $DPKGSTATE; fi
    if [ -d $PKG_PREFIX/lib/crackle ]; then rm -r $PKG_PREFIX/lib/crackle; fi
    find "$PKG_PREFIX/bin" -xtype l -exec rm {} +;
    find ~/.local/state/nix/profiles/home-manager* -xtype l -name 'home-manager-*-link' -delete
    load_library sudofunc;
    sudo_clean;
}

function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

# get info of the deb package
function get_pkg_info () {
    pkg="$(basename "$1")";
    pkgname="${pkg%%_*}";
}

# link files from ~/.local/share/crackle into ~/.local
function link_path(){
    pkg_path="$1";
    xdg_lib_path="$2"
    while read file_path
    do
        ln -s $file_path $xdg_lib_path;
    done < <(find $pkg_path -type f -maxdepth 1)
}

# link binaries from $PKGS_DIR to $PKG_PREFIX
function bin_install () {
    PKGS_DIR=${PKG_PATH}/${pkgname}
    mkdir -p ${PKGS_DIR} $PKG_PREFIX/bin;
    dpkg-deb -x "${package}" "${PKGS_DIR}";
    [ -d "${PKGS_DIR}/usr/bin" ] && link_path ${PKGS_DIR}/usr/bin ${PKG_PREFIX}/bin;
}

# set up curl and xz using apt
function setup_curlxz () {
    if ! check_cmd curl; then pkgs="curl"; fi
    if ! check_cmd xz; then pkgs+=" xz-utils"; fi
    ensure $APT_GET update;
    ensure $APT_GET install --download-only -y ${pkgs};
    while read package
    do
        get_pkg_info $package;
        bin_install;
    done < <(ls "$APTCACHE"/archives/*.deb);
}

# check if a path exists
check_path() {
    case "$PATH" in
        *.local/bin*) echo PATH is ready;;
        *) export PATH="$HOME/.local/bin:$PATH";;
    esac
}

# set up nix home manager
function setup_home-manager (){
    if ! check_cmd nix; then
        sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --no-daemon --no-channel-add;
        . $HOME/.nix-profile/etc/profile.d/nix.sh
        nix-channel --add https://nixos.org/channels/nixos-$NIX_VERSION nixpkgs
        nix-channel --update
    fi
    if ! check_cmd home-manager; then
        nix-channel --add https://github.com/nix-community/home-manager/archive/release-$NIX_VERSION.tar.gz home-manager
        nix-channel --update
        nix-shell '<home-manager>' -A install
    fi
}

# set up nix home-manager, leave no trace of apt config
function setup() {
    check_path;
    rootfstat=$(rorw);
    nixdirstat=$(rwnix);
    lsbstat=$(lsb_release -is);
    variant=$(osvariant)
    if [[ "$lsbstat" = "Ubuntu" ]] && [[ "$variant" == "Touch" ]];
    then
        if [[ ! "$nixdirstat" = "rw" ]]; then err "This version of $lsbstat $variant is not supported"; fi
        if ! check_cmd nix; then pkgsetup; fi
        if ! check_cmd nix; then setup_curlxz; fi
    elif [[ "$rootfstat" = "rw" ]];
    then
        if check_cmd apt;
        then
            load_library sudofunc;
            if ! check_cmd curl; then pkgs="curl"; fi
            if ! check_cmd xz; then pkgs+=" xz-utils"; fi
            if [[ -n "$pkgs" ]]; then sudo_run 'apt install curl xz-utils'; fi
        else
            err 'only debian based systems are currently supported';
        fi
    else
        err "$lsbstat is currently not supported";
    fi
    setup_home-manager;
    if [ -d $APTCACHE ]; then
        pkgunset;
        stat "set up complete!  To ensure that the necessary environment variables are set,
 either log in again, or type

 . /home/phablet/.nix-profile/etc/profile.d/nix.sh

 in your shell.";
    else
        stat "set up complete!";
    fi

}
