#!/usr/bin/env bash

function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

# get info of the deb package
function get_pkg_info () {
    pkg="$(basename "$1")";
    pkgname="${pkg%%_*}";
}

# link files from ~/.local/share/crackle into ~/.local
function link_path(){
    pkg_path="$1";
    xdg_lib_path="$2"
    while read file_path
    do
        ln -s $file_path $xdg_lib_path;
    done < <(find $pkg_path -type f -maxdepth 1)
}

# link binaries from $PKGS_DIR to $PKG_PREFIX
function bin_install () {
    PKGS_DIR=${PKG_PATH}/${pkgname}
    mkdir -p ${PKGS_DIR} $PKG_PREFIX/bin;
    dpkg-deb -x "${package}" "${PKGS_DIR}";
    [ -d "${PKGS_DIR}/usr/bin" ] && link_path ${PKGS_DIR}/usr/bin ${PKG_PREFIX}/bin;
}

# set up curl and xz using apt
function setup_curlxz () {
    if ! check_cmd curl; then pkgs="curl"; fi
    if ! check_cmd xz; then pkgs+=" xz-utils"; fi
    $APT_GET update;
    ensure $APT_GET install --download-only -y ${pkgs};
    while read package
    do
        get_pkg_info $package;
        bin_install;
    done < <(ls "$APTCACHE"/archives/*.deb);
}

# check if a path exists
check_path() {
    case "$PATH" in
        *.local/bin*) echo PATH is ready;;
        *) export PATH="$HOME/.local.bin:$PATH";;
    esac
}

# set up nix home manager
function setup_home-manager (){
    [ ! -d /nix ] && err "please test this on the latest focal development update"
    sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --no-daemon
    . /home/phablet/.nix-profile/etc/profile.d/nix.sh
    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update
    nix-shell '<home-manager>' -A install
}

# set up nix home-manager, leave no trace of apt config
function setup() {
    pkgsetup;
    setup_curlxz;
    check_path;
    setup_home-manager;
    pkgunset;
}
