#!/bin/bash
# pulled out of https://sh.rustup.rs/
checkro() {
    if ! check_cmd rorw;
    then
        export PATH="$PATH:~/.local/bin"
	echo please add ~/.local/bin to your PATH;
    fi
    if [[ $(rorw) = "rw" ]]; then
        echo "remounting rootfs as readonly....";
        remount || err "remounting failed! crackle works best on a readonly rootfs";
    fi
}

check_cmd() {
    command -v "$1" > /dev/null 2>&1
}

say() {
    printf '%s\n' "$1"
}

err() {
    say "Crackle: $1" >&2
    exit 100
}

stat() {
    say "$1" >&2
    exit 0
}

upd() {
    lib=$(basename $1)
    if [[ ! -f "$2/$lib" ]]; then
	say "installing $lib..." >&2
	cp $1 $2
    elif ! diff -q $1 $2; then
	say "updating $lib..." >&2
	cp $1 $2
    fi
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
    if ! "$@"; then exit 1; fi
}

get_architecture() {
    bash --version|arch_triplet
}
