#!/bin/bash

# say something
say() {
    printf '\r%s\n' "$1"
}

# download the latest release of crackle to $HOME/Downloads
download_crackle() {
	say "downloading latest version"
	wget -q https://github.com/tuxecure/crackle/releases/latest/download/crackle.zip -O $HOME/Downloads/crackle.zip
}

# unzip to $HOME/crackle
unzip_crackle() {
        [[ -d $HOME/crackle ]] && rm -r $HOME/crackle;
	say "unpacking..."
	unzip -q $HOME/Downloads/crackle.zip -d $HOME/crackle
}

# upgrade crackle itself to the latest release
upgrade_crackle() {
	[[ ! -f $HOME/Downloads/crackle.zip ]] && download_crackle;
	[[ ! -d $HOME/crackle ]] && unzip_crackle;
    $HOME/crackle/crackle setup
	say "cleaning up..."
	rm -r $HOME/crackle;
	rm $HOME/Downloads/crackle.zip;
	say "done!"
}

operation="${1}"
case $operation in
	"install")upgrade_crackle;;
	"setup")upgrade_crackle;;
esac
